// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qawrjbkzpprmdjdzbtva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhd3JqYmt6cHBybWRqZHpidHZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MzU3NTEsImV4cCI6MjA1OTQxMTc1MX0.6M6NfYtJ6CQcAtRKBD_9YhLBImdyvATMH9rfpg0iWyY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);